# Generated by Django 5.1.7 on 2025-03-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
